# Generated by Django 4.2.16 on 2025-08-01 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='note',
            field=models.TextField(blank=True, default=''),
        ),
    ]
