# Generated by Django 4.2.16 on 2025-08-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainapp', '0002_uploadedimage_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='category',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
